config/routes.rb
Rails.application.routes.draw do
  # 管理者
  devise_for :admins
  namespace :admin do
  	resources :users, only: [:show, :index, :destroy]
    get '/menu' => 'users#menu', as: 'menu'
    resources :spots
    resources :posts, only: [:show, :edit, :update, :index, :destroy]
    resources :categories, only: [:index, :create, :edit, :update, :destroy]
  end

  # ユーザ
  root to: 'spots#index'
  get '/about' => 'spots#about'
  devise_for :users
  resources :users, only: [:edit, :update, :show]
  get 'users/:id/exit' => 'users#exit', as: 'exit'
  get 'users/:id/mypage' => 'users#mypage', as: 'mypage'
  resources :spots, only: [:index, :show] do
    resource :likes, only: [:create, :destroy]
  end
  resources :likes, only: [:index]
  delete 'likes/destroy_all' => 'likes#destroy_all', as: 'destroy_all'
  resources :posts, only: [:create, :show, :edit, :update, :destroy] do
    collection do
      get :spots_select
    end
  end
  get 'posts/new/:id' => 'posts#new' , as:'new_post'
  get '/news' => 'posts#news' ,as:'news'
  get 'posts/autocomplete_spot/:term' => 'posts#autocomplete_spot'
  resources :plans, only: [:create, :index, :edit, :update, :destroy]
  get 'plans/new/:id' => 'plans#new', as:'new_plan'
  get 'plans/autocomplete_spot/:term' => 'plans#autocomplete_spot'
  resources :destinations, only: [:new, :create, :edit, :update, :destroy] do
    collection do
      get :spots_select
    end
  end
end

app/models/spot.rb
class Spot < ApplicationRecord
	acts_as_paranoid
	attachment :image

	has_many :posts
	belongs_to :category
	belongs_to :destination

	scope :autocomplete, ->(term) {
		where("name LIKE ?" , "#{term}%").order(:name)
	}

	geocoded_by :address
	after_validation :geocode
	# モデル登録時と住所(address)変更時にgeocoderにより、緯度・経度のデータが登録・更新される。

	has_many :likes, dependent: :destroy
	def liked_by?(user)
		likes.where(user_id: user.id).exists?
	end

	validates :name, presence: true
	validates :address, presence: true
	validates :content, presence: true
end

app/controllers/admin/spots_controller.rb
class Admin::SpotsController < ApplicationController
	def new
		if admin_signed_in?
			@spot = Spot.new
		else
			redirect_to root_path
		end
	end

	def create
		@category = Category.find(params[:spot][:category_id])
		@spot = Spot.new(spot_params)
		@spot.category_id = @category.id
		if @spot.save
			flash[:success] = "観光地を登録しました。"
			redirect_to new_admin_spot_path
		else
			render 'new'
		end
	end

	def edit
		if admin_signed_in?
			@spot = Spot.find(params[:id])
		else
			redirect_to root_path
		end
	end

	def update
		@category = Category.find_by(name: params[:spot][:category_id])
		@spot = Spot.find(params[:id])
		@spot.category_id = @spot.category.id
		if @spot.update(spot_params)
			redirect_to admin_spot_path(params[:id])
		else
			render 'edit'
		end
	end

	def destroy
		@spot = Spot.find(params[:id])
		@spot.destroy
		redirect_to admin_spots_path
	end

	def index
		if admin_signed_in?
			@spots = Spot.all
		else
			redirect_to root_path
		end
	end

	def show
		if admin_signed_in?
			@spot = Spot.find(params[:id])
		else
			redirect_to root_path
		end
	end

	private
	def spot_params
		params.require(:spot).permit(:name, :address, :image, :content, :latitude, :longitude)
	end
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  def index
    if Rails.env.producion?
      @random = Spot.order("RAND()").limit(6)
    else
      @random = Spot.order("RANDOM()").limit(6)
    end
    @spots = Spot.all
    @categories = Category.all
  end

  def show
    @spot = Spot.find(params[:id])
    @posts = Post.where(spot_id: @spot.id)
    post_images = PostImage.joins(:@post).where(post_id: {spot_id: @spot.id})
  end
end

app/helpers/admin/spots_helper.rb
module Admin::SpotsHelper
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/views/spots/about.html.erb
<div class="about_page">
  <div class="about_box">
    <ul class="about_first">
      <li>屋久島に興味のあるすべての方のためのサイトです。</li>
    </ul>
    <ul class="about_second">
      <li>観光地について知りたい</li>
      <li>旅行の計画を立てたい</li>
      <li>遊びに行った感想を投稿したい</li>
    </ul>
    <ul class="about_third">
      <li>そんなときにご利用ください。</li>
    </ul>
  </div>
</div>

app/views/spots/index.html.erb
<div class="top-page">
  <div class="spot_index">

    <div class="theTarget">
      <div class="pic1"></div>
      <div class="pic2"></div>
      <div class="pic3"></div>
      <div class="pic4"></div>
      <div class="pic5"></div>
    </div>

    <div class="tab-index clearfix">

      <div class="tab1">
        <div class="tab-title">旅行の計画を立てる</div>
      </div>

      <div class="tab2">
        <div class="tab-title">屋久島について知る</div>
          <div class="category-index">
          <% @categories.each do |category| %>
            <div class="spot_category">
              <div class="category_name"><%= category.name %></div>
            </div>
          <% end %>
        </div>

        <% @random.each_slice(2) do |spot1, spot2| %>
        <div class="tab-spot-index">
          <div class="random-image">
            <%= link_to spot_path(spot1.id) do %>
              <%= attachment_image_tag spot1, :image, :fill, 200, 150 %>
            <% end %>
          </div>
          <div class="random-image">
            <%= link_to spot_path(spot2.id) do %>
              <%= attachment_image_tag spot2, :image, :fill, 200, 150 %>
            <% end %>
          </div>
        </div>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/spots/show.html.erb
<div class="spot_show">

	<div class="spot_show_first clearfix">
		<div id="map"></div>

		<div class="spot_show_image">
			<%= attachment_image_tag @spot, :image, :fill, 530, 400 %>
		</div>
	</div>

	<div class="spot_show_second clearfix">

		<div class="spot_images">
	    <% @posts.each do |post| %>
	      <% post.post_images.each_slice(2) do |image1, image2| %>
	        <div  class="spot_image">
	        	<div class="spot_image_first">
		        	<% if image1 != nil %>
			          <%= link_to post_path(post.id) do %>
			            <%= attachment_image_tag image1, :image, :fill, 200, 150 %>
			          <% end %>
			        <% end %>
			       </div>
			       <div class="spot_image_second">
		        	<% if image2 != nil %>
			          <%= link_to post_path(post.id) do %>
			            <%= attachment_image_tag image2, :image, :fill, 200, 150 %>
			          <% end %>
			        <% end %>
			      </div>
	        </div>
	      <% end %>
	     <% end %>
		</div>

		<div class="spot_show_text">

		<% if user_signed_in? %>
			<div class="spot_show_name"><%= @spot.name %></div>
      <div id="likes_buttons_<%= @spot.id %>">
         <%= render partial: 'likes/like', locals: { spot: @spot} %>
      </div>
      <div class="post_new_button">
      	<%= link_to "投稿", new_post_path(@spot.id) %>
      </div>
			<div class="spot_category">
				<div class="category_name"><%= @spot.category.name %></div>
			</div>
			<div class="address">
				<label>住所</label>
				<%= @spot.address %>
			</div>
			<div class="content"><%= @spot.content %></div>
		<% else %>
			<div class="spot_show_name"><%= @spot.name %></div>
			<div class="spot_category">
				<div class="category_name"><%= @spot.category.name %></div>
			</div>
			<div class="address">
				<label>住所</label>
				<%= @spot.address %>
			</div>
			<div class="content"><%= @spot.content %></div>
		<% end %>

			<% if @posts.any? %>
				<% @posts.each do |post| %>
					<div class="spot_post_show">
						<div class="spot_post_date">
							<label>投稿日</label>
								<%= post.created_at.strftime("%Y/%m/%d") %>
						</div>
						<div class="spot_visit_day">
							<label>訪問日</label>
								<%= post.visit_date.strftime("%Y/%m/%d") %>
							<div class="spot_post_user"><%= post.user.name %>さん</div>
						</div>
						<div class="spot_comment">
							<%= post.impression %>
						</div>
					</div>
				<% end %>
			<% else %>
				<div class="spot_comment_none">投稿はまだありません。</div>
			<% end %>
		</div>
	</div>

</div>



<script>
function initMap(){
  let map = new google.maps.Map(document.getElementById('map'), {
  center: {lat: <%= @spot.latitude %>, lng: <%= @spot.longitude %>},
  zoom: 15
  });
  let marker = new google.maps.Marker({
     position: {lat: <%= @spot.latitude %>, lng: <%= @spot.longitude %>},
     map: map
  });
}
</script>

<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GMAP_API_KEY'] %>&callback=initMap" async defer></script>