config/routes.rb
Rails.application.routes.draw do
  # 管理者
  devise_for :admins
  namespace :admin do
  	resources :users, only: [:show, :index, :destroy]
    get '/menu' => 'users#menu', as: 'menu'
    resources :spots
    resources :posts, only: [:show, :edit, :update, :index, :destroy]
    resources :categories, only: [:index, :create, :edit, :update, :destroy]
  end

  # ユーザ
  root to: 'spots#index'
  get '/about' => 'spots#about'
  devise_for :users
  resources :users, only: [:edit, :update, :show]
  get 'users/:id/exit' => 'users#exit', as: 'exit'
  get 'users/:id/mypage' => 'users#mypage', as: 'mypage'
  resources :spots, only: [:index, :show] do
    resource :likes, only: [:create, :destroy]
  end
  resources :likes, only: [:index]
  delete 'likes/destroy_all' => 'likes#destroy_all', as: 'destroy_all'
  resources :posts, only: [:create, :show, :edit, :update, :destroy] do
    collection do
      get :spots_select
    end
  end
  get 'posts/new/:id' => 'posts#new' , as:'new_post'
  get '/news' => 'posts#news' ,as:'news'
  get 'posts/autocomplete_spot/:term' => 'posts#autocomplete_spot'
  resources :plans, only: [:create, :index, :edit, :update, :destroy]
  get 'plans/new/:id' => 'plans#new', as:'new_plan'
  get 'plans/autocomplete_spot/:term' => 'plans#autocomplete_spot'
  resources :destinations, only: [:new, :create, :edit, :update, :destroy] do
    collection do
      get :spots_select
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :spots

  validates :name, presence: true
end

app/models/destination.rb
class Destination < ApplicationRecord
  belongs_to :plan
  belongs_to :category
  belongs_to :spot
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :spot

  validates_uniqueness_of :spot_id, scope: :user_id
end

app/models/plan.rb
class Plan < ApplicationRecord
  acts_as_paranoid

  belongs_to :user
  has_many :destinations, inverse_of: :plan
  accepts_nested_attributes_for :destinations, allow_destroy: true

  validates :name, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :spot
	belongs_to :user
	has_many :post_images, dependent: :destroy
	accepts_nested_attributes_for :post_images, allow_destroy: true

  validates :impression, presence: true
end

app/models/post_image.rb
class PostImage < ApplicationRecord
	belongs_to :post

	attachment :image

  validates :image, presence: true
end

app/models/spot.rb
class Spot < ApplicationRecord
	acts_as_paranoid
	attachment :image

	has_many :posts
	belongs_to :category
	belongs_to :destination

	scope :autocomplete, ->(term) {
		where("name LIKE ?" , "#{term}%").order(:name)
	}

	geocoded_by :address
	after_validation :geocode
	# モデル登録時と住所(address)変更時にgeocoderにより、緯度・経度のデータが登録・更新される。

	has_many :likes, dependent: :destroy
	def liked_by?(user)
		likes.where(user_id: user.id).exists?
	end

	validates :name, presence: true
	validates :address, presence: true
	validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :likes, dependent: :destroy
  has_many :plans, dependent: :destroy

  validates :name, presence: true, length: { maximum: 15 }
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    @spot = Spot.find(params[:spot_id])
    like = current_user.likes.build(spot_id: params[:spot_id])
    like.save
  end
  def destroy
    @spot = Spot.find(params[:spot_id])
    like = Like.find_by(spot_id: params[:spot_id], user_id: current_user.id)
    like.destroy
  end

  def index
    @user = current_user
    @likes = @user.likes
  end

  def destroy_all
    @likes = Like.where(id: params[:likes])
    @likes.destroy_all
    redirect_to likes_path
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :authenticate_user!

  def autocomplete_spot
    spot_suggestions = Spot.autocomplete(params[:term]).pluck(:name)
    respond_to do |format|
      format.html
      format.json{
        render json: spot_suggestions
      }
    end
  end

  def spots_select
    if request.xhr?
      render partial: 'spots', locals: {category_id: params[:category_id]}
    end
  end

  def new
    @plan = Plan.find(params[:id])
    @destination = Destination.new
    @spot = Spot.new
  end

  def create
    @plan = Plan.new(plan_params)
    @user = current_user
    @plans = @user.plans
    @plan = @user.plans.create(plan_params)
    if @plan.save
      redirect_to new_plan_path(@plan.id)
    else
      render action: :index
    end
  end

  def index
    @user = current_user
    @plans = @user.plans
    @plan = Plan.new
  end

  def edit
    @plan = Plan.find(params[:id])
    @destination = Destination.where(plan_id: @plan.id)
    @spots = Spot.where(destination_id: @destination.id)
  end

  def update
    @plan = Plan.find(params[:id])
    @destination = Destination.where(plan_id: @plan.id)
    @spot = Spot.find(params[:destination][:spot])

    if @destination.length == 0
      @destination = Destination.new
    else
      @destinatin.spot_id = @spot.id
    end

    if @plan.update(plan_params)
      redirect_to plans_path
    else
      render "edit"
    end
  end

  def destroy
    @plan = Plan.find(params[:id])
    @plan.destroy
    redirect_to plans_path
  end

  private
  def plan_params
    params.require(:plan).permit(:name, :start_date, :end_date)
  end

  def nest_plan_params
    params.require(:plan).permit(:name, :start_date, :end_date,
      destinations_attributes: [:id, :time, :to_do, :_destroy])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!

  def spots_select
    if request.xhr?
      render partial: 'posts/spots', locals: {category_id: params[:category_id]}
    end
  end

	def new
		@spot = Spot.find(params[:id])
		@post = Post.new
		@post_image = @post.post_images.build
		@post.spot_id = @spot.id
	end

  def news
    @post = Post.new
    @spot = @post.spot
    @post_image = @post.post_images.build
  end

	def create
		if @spot != nil
			@spot = Spot.find(params[:post][:spot_id])
			@post = Post.new(post_params)
		else
			@post = Post.new(post_params)
			@spot = Spot.find(params[:spot][:spot])
		end
		@post.user_id = current_user.id
		@post.spot_id = @spot.id
		if @post.save
  		redirect_to post_path(@post.id)
		end
	end

	def show
		@post = Post.find(params[:id])
		@post_images = PostImage.where(post_id: @post.id)
	end

	def edit
		@post = Post.find(params[:id])
		@post_images = PostImage.where(post_id: @post.id)
	end

	def update
		@post = Post.find(params[:id])
		@spot = @post.spot
		@post.spot_id = @spot.id
		if @post.update(post_params)
			redirect_to post_path(@post.id)
		else
			render 'edit'
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to mypage_path(current_user.id)
	end

	private
	def post_params
		params.require(:post).permit(:impression, :visit_date, :spot_id,
			post_images_attributes: [:id, :image, :_destroy])
	end
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  def index
    if Rails.env.producion?
      @random = Spot.order("RAND()").limit(6)
    else
      @random = Spot.order("RANDOM()").limit(6)
    end
    @spots = Spot.all
    @categories = Category.all
  end

  def show
    @spot = Spot.find(params[:id])
    @posts = Post.where(spot_id: @spot.id)
    post_images = PostImage.joins(:@post).where(post_id: {spot_id: @spot.id})
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/helpers/usres_helper.rb
module UsresHelper
end

app/views/likes/_like.html.erb
<div class="heart">
  <% if @spot.liked_by?(current_user) %>
    <li>
      <%= link_to spot_likes_path(@spot.id), method: :delete, remote: true do %>
        <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
      <% end %>
    </li>
  <% else %>
    <li>
      <%= link_to spot_likes_path(@spot.id), method: :post, remote: true do %>
        <i class="fa fa-heart-o" aria-hidden="true"></i>
      <% end %>
    </li>
  <% end %>
</div>

app/views/likes/create.js.erb
$('#likes_buttons_<%= @spot.id %>').html("<%= j(render partial: 'likes/like', locals: {spot: @spot}) %>");

app/views/likes/destroy.js.erb
$('#likes_buttons_<%= @spot.id %>').html("<%= j(render partial: 'likes/like', locals: {spot: @spot}) %>");

app/views/likes/index.html.erb
<div class="likes_index">
  <div class="likes_text">
    <div class="likes-count">
      【いいね: <%= @likes.count %>件】
    </div>

    <% if @likes.any? %>

        <% @likes.each_slice(4) do |like1, like2, like3, like4| %>
          <div class="likes_table clearfix">
            <div class="like_first">
              <% if like1 != nil%>
                <div class="checkbox">
                  <%= check_box_tag 'likes[]', like1.id, false, {id: like1.id, form: "formtag"} %>
                </div>

                <div class="likes_photo">
                  <%= link_to spot_path(like1.spot.id) do %>
                    <%= attachment_image_tag like1.spot, :image, :fill, 200, 150, format: 'jpg', fallback: "no_image.jpg" %>
                  <% end %>
                </div>

                <div class="likes_category">
                  <%= like1.spot.category.name %>
                </div>

                <div class="likes_spot_name">
                  <%=link_to like1.spot.name, spot_path(like1.spot.id), class: "like_spot_name" %>
                </div>
              <% end %>
            </div>

            <div class="like_second">
              <% if like2 != nil%>
                <div class="checkbox">
                  <%= check_box_tag 'likes[]', like2.id, false, {id: like2.id, form: "formtag"} %>
                </div>

                <div class="likes_photo">
                  <%= link_to spot_path(like2.spot.id) do %>
                    <%= attachment_image_tag like2.spot, :image, :fill, 200, 150, format: 'jpg', fallback: "no_image.jpg" %>
                  <% end %>
                </div>

                <div class="likes_category">
                  <%= like2.spot.category.name %>
                </div>

                <div class="likes_spot_name">
                  <%=link_to like2.spot.name, spot_path(like2.spot.id), class: "like_spot_name" %>
                </div>
              <% end %>
            </div>

            <div class="like_third">
              <% if like3 != nil%>
                <div class="checkbox">
                  <%= check_box_tag 'likes[]', like3.id, false, {id: like3.id, form: "formtag"} %>
                </div>

                <div class="likes_photo">
                  <%= link_to spot_path(like3.spot.id) do %>
                    <%= attachment_image_tag like3.spot, :image, :fill, 200, 150, format: 'jpg', fallback: "no_image.jpg" %>
                  <% end %>
                </div>

                <div class="likes_category">
                  <%= like3.spot.category.name %>
                </div>

                <div class="likes_spot_name">
                    <%=link_to like3.spot.name, spot_path(like3.spot.id), class: "like_spot_name" %>
                </div>
              <% end %>
            </div>

            <div class="like_fourth">
              <% if like4 != nil%>
                <div class="checkbox">
                  <%= check_box_tag 'likes[]', like4.id, false, {id: like4.id, form: "formtag"} %>
                </div>

                <div class="likes_photo">
                  <%= link_to spot_path(like4.spot.id) do %>
                    <%= attachment_image_tag like3.spot, :image, :fill, 200, 150, format: 'jpg', fallback: "no_image.jpg" %>
                  <% end %>
                </div>

                <div class="likes_category">
                  <%= like4.spot.category.name %>
                </div>

                <div class="likes_spot_name">
                    <%=link_to like4.spot.name, spot_path(like4.spot.id), class: "like_spot_name" %>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>

      <div class="change-position">
        <%= form_tag(destroy_all_path, method: :delete, id:"formtag") do %>
          <div class="change-position">
            <%= submit_tag "チェックしたスポットを削除", class: "like_delete_btn" %>
          </div>
        <% end %>
      </div>

    <% else %>
      <div class="likes_none">
        <p>いいねはまだありません。</p>
      </div>
    <% end %>

  </div>
</div>

<div class="user_mypage_link">
  <%= link_to "マイページ", mypage_path(current_user.id) %>
</div>

app/views/plans/_destination_fields.html.erb
<div class="nested-fields">
  <div class="destination-edit clearfix">
    <div class="destination_time clearfix">
      <%= f.time_select :time, class: 'form_date_select', :minute_step => 15 %>
    </div>

    <div class="destination_select">

      <div class="destination_spot">
        <%= f.label :spot, "スポット" %>
        <%= collection_select :destination, :spot, Spot.all, :id, :name %>
      </div>


      <div class="plan_content">
        <%= f.text_area :to_do, class: 'form-control' %>
      </div>
    </div>

    <div class="destination_delete">
      <%= link_to_remove_association '削除', f %>
    </div>
  </div>
</div>

    <script>
    var counter = 0;
    document.addEventListener("turbolinks:load", function() {
      $('.nested-fields')
        .on('cocoon:after-insert', function(e, insertedItem) {
          $(insertedItem).find('.spotForm').attr('id', 'spotForm_' + counter++);

          $(".spotForm").change(function() {
            var id = $(this).attr('id');

            $(document).on('change', '#parent', function() {
              console.log(this);
              return $.ajax({
                type: 'GET',
                url: '/destinations/spots_select',
                data: {
                  category_id: $(this).val()
                }
              }).done(function(data) {
                return $('.spotForm').html(data);
              });
            });
        })
    })
    </script>

app/views/plans/_form.html.erb
<div class="field">
  <%= f.fields_for :destinations do |destination| %>
    <%= render 'destination_fields', f: destination %>
  <% end %>

  <div id="destination_links">
    <%= link_to_add_association '行き先の追加',f, :destinations %>
  </div>
</div>

app/views/plans/_spots.html.erb
<%= collection_select :destination, :spot, Spot.where(category_id: category_id), :id, :name, class: "spotFom" %>

app/views/plans/edit.html.erb
<div class="destination_edit">
  <%= form_for @plan do |f| %>

    <div class="plan_show clearfix">
      <div class="plan_show_name clearfix">
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class="plan_date_des">
        <div class="plan_start clearfix">
          <%= f.text_field :start_date, class:"form-control datetimepicker-input", data: {toggle: "datetimepicker", target: ".datetimepicker-input"} %>
        </div>
        <div class="plan_text">
          〜
        </div>
        <div class="plan_end">
          <%= f.text_field :end_date, class:"form-control datetimepicker-input", data: {toggle: "datetimepicker", target: ".datetimepicker-input"} %>
        </div>
            <script type="text/javascript">
              $(function () {
                $(".datetimepicker-input").datetimepicker({
                format:'YYYY/MM/DD'
                });
              });
            </script>
      </div>
    </div>

    <div class="destination_form">
      <%= render 'form', destination: @destination,f:f %>
    </div>

    <div class="destination_submit">
      <%= f.submit "保存", class: "btn btn-success" %>
    </div>

  <% end %>
</div>

app/views/plans/index.html.erb
<div class="plans_index">
  <div class="plan_new">
    <%= form_for @plan do |f| %>

      <div class="form-group  clearfix">
        <div class="plan_label"><%= f.label :name, "プラン" %></div>
        <div class="plan_name"><%= f.text_field :name, class: 'form-control' %></div>
      </div>

      <div class="form-group clearfix">
        <div class="plan_date_label"><%= f.label :start_date, "日程" %></div>
        <div class="plan_date">
          <div class="start_date">
            <%= f.text_field :start_date, class:"form-control datetimepicker-input",
            data: {toggle: "datetimepicker", target: ".datetimepicker-input"}, placeholder: "年/月/日" %>
          </div>
          <div class="plan_date_text">
            〜
          </div>
          <div class="end_date">
            <%= f.text_field :end_date, class:"form-control datetimepicker-input",
            data: {toggle: "datetimepicker", target: ".datetimepicker-input"}, placeholder: "年/月/日" %>
          </div>
          <script type="text/javascript">
            $(function () {
              $(".datetimepicker-input").datetimepicker({
              format:'YYYY/MM/DD'
              });
            });
          </script>
        </div>
      </div>

      <div class="plan_submit">
        <%= f.submit '登録', class: 'btn btn-primary' %>
      </div>

    <% end %>
  </div>

  <div class="user_plan_index">
    <% if @plans.any? %>
      <% @plans.each do |plan| %>
        <div class="user_plans clearfix">
          <div class="user_plan_photo">
          </div>

          <div class="user_plan_name clearfix">
            <%= plan.name %>
          </div>

          <div class="user_plan_start">
            <%= plan.start_date %>
          </div>

          <div class="user_plan_text">
            〜
          </div>

          <div class="user_plan_end">
            <%= plan.end_date %>
          </div>

          <div class="user_plan_edit">
            <%= link_to "詳細", edit_plan_path(plan.id) %>
              |
            <%= link_to "削除", plan_path(plan.id), method: :delete, data:
             { confirm: "本当に削除しますか？",
               cancel: "戻る",
               commit: "削除"}, title:"削除の確認" %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/plans/new.html.erb
<div class="destination_edit">
  <%= form_for @plan do |f| %>

    <div class="plan_show clearfix">
      <div class="plan_show_name clearfix">
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class="plan_date_des">
        <div class="plan_start clearfix">
          <%= f.text_field :start_date, class:"form-control datetimepicker-input", data: {toggle: "datetimepicker", target: ".datetimepicker-input"} %>
        </div>
        <div class="plan_text">
          〜
        </div>
        <div class="plan_end">
          <%= f.text_field :end_date, class:"form-control datetimepicker-input", data: {toggle: "datetimepicker", target: ".datetimepicker-input"} %>
        </div>
            <script type="text/javascript">
              $(function () {
                $(".datetimepicker-input").datetimepicker({
                format:'YYYY/MM/DD'
                });
              });
            </script>
      </div>
    </div>

    <div class="destination_form">
      <%= render 'form', destination: @destination,f:f %>
    </div>

    <div class="destination_submit">
      <%= f.submit "保存", class: "btn btn-success" %>
    </div>

  <% end %>
</div>