config/routes.rb
Rails.application.routes.draw do
  # 管理者
  devise_for :admins
  namespace :admin do
  	resources :users, only: [:show, :index, :destroy]
    get '/menu' => 'users#menu', as: 'menu'
    resources :spots
    resources :posts, only: [:show, :edit, :update, :index, :destroy]
    resources :categories, only: [:index, :create, :edit, :update, :destroy]
  end

  # ユーザ
  root to: 'spots#index'
  get '/about' => 'spots#about'
  devise_for :users
  resources :users, only: [:edit, :update, :show]
  get 'users/:id/exit' => 'users#exit', as: 'exit'
  get 'users/:id/mypage' => 'users#mypage', as: 'mypage'
  resources :spots, only: [:index, :show] do
    resource :likes, only: [:create, :destroy]
  end
  resources :likes, only: [:index]
  delete 'likes/destroy_all' => 'likes#destroy_all', as: 'destroy_all'
  resources :posts, only: [:create, :show, :edit, :update, :destroy] do
    collection do
      get :spots_select
    end
  end
  get 'posts/new/:id' => 'posts#new' , as:'new_post'
  get '/news' => 'posts#news' ,as:'news'
  get 'posts/autocomplete_spot/:term' => 'posts#autocomplete_spot'
  resources :plans, only: [:create, :index, :edit, :update, :destroy]
  get 'plans/new/:id' => 'plans#new', as:'new_plan'
  get 'plans/autocomplete_spot/:term' => 'plans#autocomplete_spot'
  resources :destinations, only: [:new, :create, :edit, :update, :destroy] do
    collection do
      get :spots_select
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :spots

  validates :name, presence: true
end

app/models/destination.rb
class Destination < ApplicationRecord
  belongs_to :plan
  belongs_to :category
  belongs_to :spot
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :spot

  validates_uniqueness_of :spot_id, scope: :user_id
end

app/models/plan.rb
class Plan < ApplicationRecord
  acts_as_paranoid

  belongs_to :user
  has_many :destinations, inverse_of: :plan
  accepts_nested_attributes_for :destinations, allow_destroy: true

  validates :name, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :spot
	belongs_to :user
	has_many :post_images, dependent: :destroy
	accepts_nested_attributes_for :post_images, allow_destroy: true

  validates :impression, presence: true
end

app/models/post_image.rb
class PostImage < ApplicationRecord
	belongs_to :post

	attachment :image

  validates :image, presence: true
end

app/models/spot.rb
class Spot < ApplicationRecord
	acts_as_paranoid
	attachment :image

	has_many :posts
	belongs_to :category
	belongs_to :destination

	scope :autocomplete, ->(term) {
		where("name LIKE ?" , "#{term}%").order(:name)
	}

	geocoded_by :address
	after_validation :geocode
	# モデル登録時と住所(address)変更時にgeocoderにより、緯度・経度のデータが登録・更新される。

	has_many :likes, dependent: :destroy
	def liked_by?(user)
		likes.where(user_id: user.id).exists?
	end

	validates :name, presence: true
	validates :address, presence: true
	validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :likes, dependent: :destroy
  has_many :plans, dependent: :destroy

  validates :name, presence: true, length: { maximum: 15 }
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
	def index
    if admin_signed_in?
		  @users = User.all
    else
      redirect_to root_path
    end
	end

	def show
    if admin_signed_in?
		  @user = User.find(params[:id])
    else
      redirect_to root_path
    end
	end

	def edit
    if admin_signed_in?
		  @user = User.find(params[:id])
    else
      redirect_to root_path
    end
	end

	def update
		@user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_path(@user.id)
    else
      render 'index'
    end
  end

	def destroy
		@user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path
  end

  def user_params
    params.require(:user).permit(:id, :name, :email)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    @spot = Spot.find(params[:spot_id])
    like = current_user.likes.build(spot_id: params[:spot_id])
    like.save
  end
  def destroy
    @spot = Spot.find(params[:spot_id])
    like = Like.find_by(spot_id: params[:spot_id], user_id: current_user.id)
    like.destroy
  end

  def index
    @user = current_user
    @likes = @user.likes
  end

  def destroy_all
    @likes = Like.where(id: params[:likes])
    @likes.destroy_all
    redirect_to likes_path
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :authenticate_user!

  def autocomplete_spot
    spot_suggestions = Spot.autocomplete(params[:term]).pluck(:name)
    respond_to do |format|
      format.html
      format.json{
        render json: spot_suggestions
      }
    end
  end

  def spots_select
    if request.xhr?
      render partial: 'spots', locals: {category_id: params[:category_id]}
    end
  end

  def new
    @plan = Plan.find(params[:id])
    @destination = Destination.new
    @spot = Spot.new
  end

  def create
    @plan = Plan.new(plan_params)
    @user = current_user
    @plans = @user.plans
    @plan = @user.plans.create(plan_params)
    if @plan.save
      redirect_to new_plan_path(@plan.id)
    else
      render action: :index
    end
  end

  def index
    @user = current_user
    @plans = @user.plans
    @plan = Plan.new
  end

  def edit
    @plan = Plan.find(params[:id])
    @destination = Destination.where(plan_id: @plan.id)
    @spots = Spot.where(destination_id: @destination.id)
  end

  def update
    @plan = Plan.find(params[:id])
    @destination = Destination.where(plan_id: @plan.id)
    @spot = Spot.find(params[:destination][:spot])

    if @destination.length == 0
      @destination = Destination.new
    else
      @destinatin.spot_id = @spot.id
    end

    if @plan.update(plan_params)
      redirect_to plans_path
    else
      render "edit"
    end
  end

  def destroy
    @plan = Plan.find(params[:id])
    @plan.destroy
    redirect_to plans_path
  end

  private
  def plan_params
    params.require(:plan).permit(:name, :start_date, :end_date)
  end

  def nest_plan_params
    params.require(:plan).permit(:name, :start_date, :end_date,
      destinations_attributes: [:id, :time, :to_do, :_destroy])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :current_user, only: [:edit, :update]

	def show
		@user = User.find(params[:id])
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		user = User.find(params[:id])
		if user.update(user_params)
			redirect_to mypage_path
		else
			render "edit"
		end
	end

	def mypage
		@user = User.find(params[:id])
	end

	def exit
		@user = User.find(params[:id])
	end

	private
	def user_params
		params.require(:user).permit(:name, :email, :password)
	end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/helpers/usres_helper.rb
module UsresHelper
end

app/views/admin/users/index.html.erb
<div class="admin_user_index">
  <h2>会員一覧</h2>
		<table class="table-striped admin_spot_table" border="2">
			<thead>
				<tr>
						<th class="text-center"><b>ID</b></th>
						<th class="text-center"><b>会員名</b></th>
						<th class="text-center"><b>メールアドレス</b></th>
				</tr>
			</thead>
			<% @users.each do |user| %>
			<tbody>
				<tr>
						<td class="text-center"><%= user.id %></td>
						<td class="text-center"><%= link_to(admin_user_path(user)) do %>
						<div><%= user.name %></div>
					<% end %>
				</td>
						<td class="admin_emails"><%= user.email %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
   <div class="row">
	<div class="col-xs-6 col-xs-offset-3">
	 <p id="pageTop"><a href="#">ページのトップへ戻る</a></p>
	</div>
   </div>
</div>

app/views/admin/users/menu.html.erb
<div class="admin_menu">
  <%= link_to "会員一覧", admin_users_path %>
  <%= link_to "スポット", admin_spots_path %>
  <%= link_to "カテゴリー", admin_categories_path %>
  <%= link_to "投稿", admin_posts_path %>
</div>

app/views/admin/users/show.html.erb
<div class="user_form user_show">
  <h2>ユーザ情報の確認</h2>

  <table class="user_field">
  	<tr>
  		<th>ユーザID</td>
  		<td><%= @user.id %></td>
  	</tr>

    <tr>
    	<th>ユーザ名</th>
    	<td><%= @user.name %></td>
  	</tr>

    <tr>
    	<th>メールアドレス</th>
    	<td><%= @user.email %></td>
  	</tr>
	</table>

  <div class="user_actions">
    <%= link_to "削除", admin_user_path(params[:id]),method: :delete, "date-comfirm" => "本当に消しますか？", class: 'admin_user_button' %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="user_form">
	<h2>アカウント情報の編集</h2>

	<%= form_for(@user) do |f| %>

		<div class="user_field">
      <%= f.label :ユーザ名 %><br>
			<%= f.text_field :name, autofocus: true, autocomplete: "name" %>
		</div>

		<div class="user_field">
			<%= f.label :メールアドレス %><br>
			<%= f.email_field :email, autocomplete: "email" %>
		</div>

		<div class="user_actions">
			<%= f.submit "保存する", class: 'button' %>
		</div>
	<% end %>
</div>

<div class="user_links">
	 <%= link_to "マイページ", mypage_path(current_user.id) %>
</div>

<div class="user_links">
	 <%= link_to "退会する", exit_path(current_user.id) %>
</div>

app/views/users/exit.html.erb
<div class="exit_message"><h3>退会後はご登録情報をご利用いただけません。</h3></div>

<div class="user_exit">
  <div class=" user_actions">
  	<%= link_to '退会する', user_registration_path, method: :delete, class: 'user_button' %>
  </div>

  <div class="user_links">
  	<%= link_to 'マイページ', mypage_path %>
  </div>
</div>

app/views/users/mypage.html.erb
<!-- <h2>マイページ</h2> -->
  <div class=" user_menu">
    <%= link_to user_path(@user.id), class: 'mypage_button' do %>
      <i class="fas fa-user-alt" style="font-size: 60px"></i>
      <div class="user_menu_text">会員情報</div>
    <% end %>

    <%= link_to news_path, class: 'mypage_button' do %>
      <i class="fas fa-pen" style="font-size: 60px"></i>
      <div class="user_menu_text">投稿</div>
    <% end %>

    <%= link_to likes_path, class: 'mypage_button' do %>
      <i class="fas fa-heart" style="font-size: 60px"></i>
      <div class="user_menu_text">お気に入り</div>
    <% end %>

    <%= link_to plans_path, class: 'mypage_button' do %>
      <i class="fas fa-book-open" style="font-size: 60px"></i>
      <div class="user_menu_text">旅のしおり</div>
    <% end %>
  </div>

  <div  class="photos">
    <% @posts.each do |post| %>
      <% post.post_images.each do |image| %>
        <div  class="photo">
          <%= link_to post_path(post.id) do %>
            <%= attachment_image_tag image, :image, :fill, 200, 150 %>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>

app/views/users/show.html.erb
<div class="user_form user_show">
  <h2>アカウント情報の確認</h2>

  <div class="user_field">
    <label>名前</label>
    <input type="text" class="form-control" value="<%= @user.name %>" readonly>
  </div>

  <div class="user_field">
    <label>メールアドレス</label>
    <input type="text" class="form-control" value="<%= @user.email %>" readonly>
  </div>

  <div class="user_actions">
    <%= link_to "編集する", edit_user_path(@user.id), class: 'user_button' %>
  </div>
</div>

<div class="user_links">
  <%= link_to "マイページ", mypage_path %>
</div>