config/routes.rb
Rails.application.routes.draw do
  # 管理者
  devise_for :admins
  namespace :admin do
  	resources :users, only: [:show, :index, :destroy]
    get '/menu' => 'users#menu', as: 'menu'
    resources :spots
    resources :posts, only: [:show, :edit, :update, :index, :destroy]
    resources :categories, only: [:index, :create, :edit, :update, :destroy]
  end

  # ユーザ
  root to: 'spots#index'
  get '/about' => 'spots#about'
  devise_for :users
  resources :users, only: [:edit, :update, :show]
  get 'users/:id/exit' => 'users#exit', as: 'exit'
  get 'users/:id/mypage' => 'users#mypage', as: 'mypage'
  resources :spots, only: [:index, :show] do
    resource :likes, only: [:create, :destroy]
  end
  resources :likes, only: [:index]
  delete 'likes/destroy_all' => 'likes#destroy_all', as: 'destroy_all'
  resources :posts, only: [:create, :show, :edit, :update, :destroy] do
    collection do
      get :spots_select
    end
  end
  get 'posts/new/:id' => 'posts#new' , as:'new_post'
  get '/news' => 'posts#news' ,as:'news'
  get 'posts/autocomplete_spot/:term' => 'posts#autocomplete_spot'
  resources :plans, only: [:create, :index, :edit, :update, :destroy]
  get 'plans/new/:id' => 'plans#new', as:'new_plan'
  get 'plans/autocomplete_spot/:term' => 'plans#autocomplete_spot'
  resources :destinations, only: [:new, :create, :edit, :update, :destroy] do
    collection do
      get :spots_select
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :spots

  validates :name, presence: true
end

app/models/destination.rb
class Destination < ApplicationRecord
  belongs_to :plan
  belongs_to :category
  belongs_to :spot
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :spot

  validates_uniqueness_of :spot_id, scope: :user_id
end

app/models/plan.rb
class Plan < ApplicationRecord
  acts_as_paranoid

  belongs_to :user
  has_many :destinations, inverse_of: :plan
  accepts_nested_attributes_for :destinations, allow_destroy: true

  validates :name, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :spot
	belongs_to :user
	has_many :post_images, dependent: :destroy
	accepts_nested_attributes_for :post_images, allow_destroy: true

  validates :impression, presence: true
end

app/models/post_image.rb
class PostImage < ApplicationRecord
	belongs_to :post

	attachment :image

  validates :image, presence: true
end

app/models/spot.rb
class Spot < ApplicationRecord
	acts_as_paranoid
	attachment :image

	has_many :posts
	belongs_to :category
	belongs_to :destination

	scope :autocomplete, ->(term) {
		where("name LIKE ?" , "#{term}%").order(:name)
	}

	geocoded_by :address
	after_validation :geocode
	# モデル登録時と住所(address)変更時にgeocoderにより、緯度・経度のデータが登録・更新される。

	has_many :likes, dependent: :destroy
	def liked_by?(user)
		likes.where(user_id: user.id).exists?
	end

	validates :name, presence: true
	validates :address, presence: true
	validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :likes, dependent: :destroy
  has_many :plans, dependent: :destroy

  validates :name, presence: true, length: { maximum: 15 }
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    @spot = Spot.find(params[:spot_id])
    like = current_user.likes.build(spot_id: params[:spot_id])
    like.save
  end
  def destroy
    @spot = Spot.find(params[:spot_id])
    like = Like.find_by(spot_id: params[:spot_id], user_id: current_user.id)
    like.destroy
  end

  def index
    @user = current_user
    @likes = @user.likes
  end

  def destroy_all
    @likes = Like.where(id: params[:likes])
    @likes.destroy_all
    redirect_to likes_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/helpers/usres_helper.rb
module UsresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YakushimaTrip</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <% self_css_path = "/assets/"+controller.controller_name  %>
    <%= stylesheet_link_tag self_css_path, :media => "all" %>

    <% self_css_path = "/assets/admin/"+controller.controller_name  %>
    <%= stylesheet_link_tag self_css_path, :media => "all" %>

    <script src="https://kit.fontawesome.com/b1ddc8e955.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
    <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>

  </head>

  <body>
    <header>
      <div class="container">
        <nav class="navbar-left">
          <% if params[:controller] == 'spots' && params[:action] == 'index' %>
            <%= link_to(root_path) do %>
              <span class="header-title">やくしま</span>
            <% end %>
          <% elsif params[:controller] == 'admin/spots' && params[:action] == 'index' %>
            <%= link_to(admin_spots_path) do %>
              <span class="header-title">やくしま</span>
            <% end %>
          <% elsif params[:controller] == 'admin/spots' || 'admin/posts' || 'admin/post_images' || 'admin/categories' || 'admin/users' %>
            <%= link_to(admin_spots_path) do %>
              <span class="header-title">やくしま</span>
            <% end %>
          <% else %>
             <%= link_to(root_path) do %>
              <span class="header-title">やくしま</span>
            <% end %>
          <% end %>
        </nav>
        <nav class="navbar-right">
          <ul>
            <!-- アドミン -->
            <% if admin_signed_in? %>
              <li>
                <span class="admin_user">
                  <%= link_to '管理者　様', admin_menu_path %>
                </span>
              </li>
              <li>
                <span class="admin_user">
                  <%= link_to "サインアウト", destroy_admin_session_path, method: :delete %>
                </span>
              </li>
            <!-- ユーザー -->
            <% elsif user_signed_in?%>
              <li>
                <span class="current_user">
                  <%= link_to (mypage_path(current_user.id)) do %>
                    <%= current_user.name %>さん
                  <% end %>
                </span>
              </li>
              <li>
                <span class="current_user">
                  <%= link_to "サインアウト", destroy_user_session_path, method: :delete %>
                </span>
              </li>
            <!-- 非ログイン -->
            <% else %>
              <li>
                <span class="signup">
                  <%= link_to "新規登録", new_user_registration_path %>
                </span>
              </li>
              <li>
                <span class="signup">
                  <%= link_to "ログイン", new_user_session_path %>
                </span>
              </li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>
    <%= yield %>
  </body>
</html>